# Generated by Django 4.0 on 2024-12-17 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testcases', '0001_initial'),
        ('account', '0001_initial'),
        ('stbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='percentilereport',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcases.testcasemodel'),
        ),
        migrations.AddField(
            model_name='natcorelease',
            name='natcos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release', to='stbs.natco'),
        ),
        migrations.AddField(
            model_name='natco',
            name='language',
            field=models.ManyToManyField(to='stbs.Language'),
        ),
        migrations.AddField(
            model_name='natco',
            name='manufacture',
            field=models.ManyToManyField(blank=True, to='stbs.STBManufacture'),
        ),
        migrations.AddField(
            model_name='nactomanufactureslanguage',
            name='device_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='natco_manufacture', to='stbs.stbmanufacture'),
        ),
        migrations.AddField(
            model_name='nactomanufactureslanguage',
            name='language_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='natco_language', to='stbs.language'),
        ),
        migrations.AddField(
            model_name='nactomanufactureslanguage',
            name='natco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='natco_info', to='stbs.natco'),
        ),
        migrations.AddField(
            model_name='historicalstbnodeconfig',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.account'),
        ),
        migrations.AddField(
            model_name='historicalstbnodeconfig',
            name='natco',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', max_length=255, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stbs.natcorelease'),
        ),
        migrations.AddField(
            model_name='historicalstbnodeconfig',
            name='stb_node',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stbs.stbnode'),
        ),
        migrations.AddField(
            model_name='historicalstbmanufacture',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.account'),
        ),
        migrations.AddField(
            model_name='historicalnatco',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.account'),
        ),
        migrations.AddField(
            model_name='historicalnactomanufactureslanguage',
            name='device_name',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stbs.stbmanufacture'),
        ),
        migrations.AddField(
            model_name='historicalnactomanufactureslanguage',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.account'),
        ),
        migrations.AddField(
            model_name='historicalnactomanufactureslanguage',
            name='language_name',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stbs.language'),
        ),
        migrations.AddField(
            model_name='historicalnactomanufactureslanguage',
            name='natco',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stbs.natco'),
        ),
        migrations.AddField(
            model_name='historicallanguage',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.account'),
        ),
    ]
